const action_types = {
    REGISTER_USER: 'REGISTER_USER',
    SET_USER: 'SET_USER',
    LOGIN_USER: 'LOGIN_USER',
    SET_RESTAURANT: 'SET_RESTAURANT',
    SET_DISH: 'SET_DISH',
    CLEAR_DISH: 'CLEAR_DISH',
    SET_MENU: 'SET_MENU',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_ORDERS: 'SET_ORDERS',
    SET_ORDER_DETAILS: 'SET_ORDER_DETAILS'
};

export default action_types;