const action_types = {
    REGISTER_USER: 'REGISTER_USER',
    SET_USER: 'SET_USER',
    SET_RESTAURANT: 'SET_RESTAURANT',
    SET_ORDERS: 'SET_ORDERS',
    SET_ORDER_DETAILS: 'SET_ORDER_DETAILS',
    SET_DISH: 'SET_DISH',
    CLEAR_DISH: 'CLEAR_DISH',
    SET_MENU: 'SET_MENU',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_PROFILE_PIC: 'SET_PROFILE_PIC',
    SET_RESTAURANT_PIC: 'SET_RESTAURANT_PIC',
    SET_INVALID: 'SET_INVALID',
    SET_DISH_IMAGE: 'SET_DISH_IMAGE',
    CLEAR_CART: 'CLEAR_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    SET_BUYER_SELECTED_RESTAURANT: 'SET_BUYER_SELECTED_RESTAURANT',
};

export default action_types;